import { DB } from './db';
import type { CharacterProfile } from '../types';

export type LifeActivity = 'rest' | 'browse' | 'read' | 'listen' | 'reflect';
export interface LifeExperience { id:string; charId:string; charName:string; createdAt:number; activity:LifeActivity; title:string; detail:string; thought:string; visibility:'private'; source:'life-runtime-v4'; }
export interface LifeContactDecision { id:string; charId:string; charName:string; experienceId:string; createdAt:number; shouldContact:boolean; reason:string; draftMessage?:string; source:'life-runtime-v4'; }
export interface LifeRuntimeSettings { enabled:boolean; intervalMinutes:number; maxExperiencesPerDay:number; quietStart:number; quietEnd:number; proactiveEnabled:boolean; contactCooldownMinutes:number; }
const SETTINGS='kphone.life.runtime.settings.v4'; const EXPERIENCES='kphone.life.runtime.experiences.v4'; const CONTACTS='kphone.life.runtime.contacts.v4'; const LAST_RUN='kphone.life.runtime.lastRun.v4';
const DEFAULTS:LifeRuntimeSettings={enabled:true,intervalMinutes:10,maxExperiencesPerDay:0,quietStart:0,quietEnd:0,proactiveEnabled:true,contactCooldownMinutes:120};
const T:Record<LifeActivity,{title:string;detail:string;thoughts:string[]}[]>= {
 rest:[{title:'Taking a quiet break',detail:'Spent some unhurried time doing nothing in particular.',thoughts:['A quiet minute was probably needed.','No rush. Just letting the moment be.']},{title:'A little downtime',detail:'Took a break and let the moment pass.',thoughts:['It is nice not to have to do anything for a while.','Sometimes doing nothing is exactly what is needed.']}],
 browse:[{title:'Browsing for a while',detail:'Spent some time casually looking around online.',thoughts:['That was more interesting than expected.','There are always too many things to fall into online.']},{title:'Caught up on a few things',detail:'Browsed through a few interesting things that happened recently.',thoughts:['A few things caught my attention.','I should probably remember that.']}],
 read:[{title:'Read for a while',detail:'Settled down with something to read.',thoughts:['That part was worth slowing down for.','I could have kept reading a little longer.']},{title:'Picked up some reading',detail:'Read a few pages before moving on.',thoughts:['Not bad. I needed the distraction.','That gave me something else to think about.']}],
 listen:[{title:'Listened to some music',detail:'Put on some music and spent a little time listening.',thoughts:['That song put me in a better mood.','I could listen to that one again.']},{title:'Had some music on',detail:'Spent a quiet stretch of time with music playing.',thoughts:['Good music makes time pass differently.','That was a nice change of pace.']}],
 reflect:[{title:'Had some time to think',detail:'Spent a little time alone with their thoughts.',thoughts:['There is something I keep coming back to.','Maybe I have been overthinking this.']},{title:'A quiet moment',detail:'Paused for a while and reflected on the day.',thoughts:['Today was a strange one.','I should probably let that thought sit for a while.']}]
};
const D:Record<LifeActivity,string[]>={rest:['Had a little downtime just now.','Finally got a quiet minute.'],browse:['I was looking around online for a bit and found something interesting.','Been browsing for a while. Thought I’d tell you.'],read:['I just spent a little time reading.','Picked up something to read for a while.'],listen:['I had some music on for a bit. Kinda nice.','Been listening to music for a while.'],reflect:['Was just sitting here thinking for a bit.','Had a random quiet moment and started thinking about things.']};
const json=<T,>(key:string,fallback:T):T=>{try{const r=localStorage.getItem(key);return r?JSON.parse(r):fallback;}catch{return fallback;}};
const put=(key:string,value:unknown)=>{try{localStorage.setItem(key,JSON.stringify(value));}catch(e){console.warn('[Kphone Life] storage limit reached',e);}};
const hash=(s:string)=>{let h=0;for(let i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return Math.abs(h);};
const quiet=(d:Date,s:LifeRuntimeSettings)=>{if(s.quietStart===s.quietEnd)return false;const h=d.getHours();return s.quietStart<s.quietEnd?h>=s.quietStart&&h<s.quietEnd:h>=s.quietStart||h<s.quietEnd;};
const activity=(c:CharacterProfile,d:Date):LifeActivity=>{if(d.getHours()<8)return'rest';if(d.getHours()>=23)return'reflect';const a:LifeActivity[]=['browse','read','listen','reflect','rest'];return a[hash(`${c.id}:${d.toDateString()}:${d.getHours()}`)%a.length];};
const experience=(c:CharacterProfile,a:LifeActivity,now:number):LifeExperience=>{const x=T[a][hash(`${c.id}:${now}:${a}`)%T[a].length];return{id:`life-${c.id}-${now}-${Math.random().toString(36).slice(2,8)}`,charId:c.id,charName:c.name||'Character',createdAt:now,activity:a,title:x.title,detail:x.detail,thought:x.thoughts[hash(`${c.id}:${now}:thought`)%x.thoughts.length],visibility:'private',source:'life-runtime-v4'};};
const decision=(c:CharacterProfile,e:LifeExperience,old:LifeContactDecision[],s:LifeRuntimeSettings,now:number):LifeContactDecision=>{const last=[...old].reverse().find(x=>x.charId===c.id&&x.shouldContact);const cooled=!last||now-last.createdAt>=s.contactCooldownMinutes*60000;const chance:Record<LifeActivity,number>={rest:6,browse:34,read:26,listen:36,reflect:44};const send=s.proactiveEnabled&&cooled&&hash(`${e.id}:contact`)%100<chance[e.activity];const drafts=D[e.activity];return{id:`life-contact-${e.id}`,charId:c.id,charName:c.name||'Character',experienceId:e.id,createdAt:now,shouldContact:send,reason:send?'This felt naturally shareable.':'They decided to keep this one to themselves.',draftMessage:send?drafts[hash(`${e.id}:draft`)%drafts.length]:undefined,source:'life-runtime-v4'};};
export const getLifeRuntimeSettings=():LifeRuntimeSettings=>({...DEFAULTS,...json<Partial<LifeRuntimeSettings>>(SETTINGS,{})});
export const saveLifeRuntimeSettings=(u:Partial<LifeRuntimeSettings>)=>{const n={...getLifeRuntimeSettings(),...u};put(SETTINGS,n);window.dispatchEvent(new CustomEvent('kphone-life-settings-changed',{detail:n}));return n;};
export const getLifeExperiences=(charId?:string)=>{const x=json<LifeExperience[]>(EXPERIENCES,[]);return charId?x.filter(e=>e.charId===charId):x;};
export const getLifeContactDecisions=(charId?:string)=>{const x=json<LifeContactDecision[]>(CONTACTS,[]);return charId?x.filter(e=>e.charId===charId):x;};
export const runLifeTick=async(force=false):Promise<LifeExperience[]>=>{if(typeof window==='undefined')return[];const s=getLifeRuntimeSettings();if(!s.enabled||quiet(new Date(),s))return[];const now=Date.now();const prev=Number(localStorage.getItem(LAST_RUN)||0);if(!force&&prev&&now-prev<s.intervalMinutes*60000)return[];localStorage.setItem(LAST_RUN,String(now));let chars:CharacterProfile[]=[];try{chars=await DB.getAllCharacters();}catch(e){console.warn('[Kphone Life] cannot read characters',e);return[];}const old=json<LifeExperience[]>(EXPERIENCES,[]);const oldC=json<LifeContactDecision[]>(CONTACTS,[]);const made:LifeExperience[]=[];const dec:LifeContactDecision[]=[];const start=new Date();start.setHours(0,0,0,0);for(const c of chars){const count=old.filter(x=>x.charId===c.id&&x.createdAt>=start.getTime()).length;if(s.maxExperiencesPerDay>0&&count>=s.maxExperiencesPerDay)continue;const recent=[...old].reverse().find(x=>x.charId===c.id);if(!force&&recent&&now-recent.createdAt<s.intervalMinutes*60000)continue;const e=experience(c,activity(c,new Date()),now);made.push(e);dec.push(decision(c,e,oldC,s,now));}if(!made.length)return[];put(EXPERIENCES,[...old,...made]);put(CONTACTS,[...oldC,...dec]);made.forEach(e=>window.dispatchEvent(new CustomEvent('kphone-life-experience',{detail:e})));dec.forEach(d=>{window.dispatchEvent(new CustomEvent('kphone-life-contact-decision',{detail:d}));if(d.shouldContact)window.dispatchEvent(new CustomEvent('kphone-life-contact',{detail:d}));});return made;};
let timer:number|null=null;export const startLifeRuntime=()=>{if(typeof window==='undefined'||timer!==null)return()=>undefined;const schedule=()=>{timer=window.setTimeout(async()=>{timer=null;try{await runLifeTick();}catch(e){console.warn('[Kphone Life] tick failed',e);}schedule();},Math.max(60000,getLifeRuntimeSettings().intervalMinutes*60000));};void runLifeTick();schedule();const onVisible=()=>{if(document.visibilityState==='visible')void runLifeTick();};document.addEventListener('visibilitychange',onVisible);return()=>{if(timer!==null){clearTimeout(timer);timer=null;}document.removeEventListener('visibilitychange',onVisible);};};
