import React, { useEffect, useState } from 'react';
import { getLifeExperiences, getLifeContactDecisions, runLifeTick, getLifeRuntimeSettings, saveLifeRuntimeSettings, type LifeExperience, type LifeContactDecision } from '../utils/lifeRuntimeV3';

const KphoneLifeApp: React.FC<{ onClose?: () => void }> = ({ onClose }) => {
  const [experiences, setExperiences] = useState<LifeExperience[]>([]);
  const [contacts, setContacts] = useState<LifeContactDecision[]>([]);
  const [running, setRunning] = useState(false);
  const [settings,setSettings]=useState(getLifeRuntimeSettings());
  const refresh = () => { setExperiences(getLifeExperiences().slice(-200).reverse()); setContacts(getLifeContactDecisions().slice(-200).reverse()); setSettings(getLifeRuntimeSettings()); };
  useEffect(() => { refresh(); const e=()=>refresh(); window.addEventListener('kphone-life-experience',e); window.addEventListener('kphone-life-contact-decision',e); window.addEventListener('kphone-life-settings-changed',e); return()=>{window.removeEventListener('kphone-life-experience',e);window.removeEventListener('kphone-life-contact-decision',e);window.removeEventListener('kphone-life-settings-changed',e);}; }, []);
  const runNow=async()=>{setRunning(true);try{await runLifeTick(true);refresh();}finally{setRunning(false);}};
  const decisions=new Map(contacts.map(x=>[x.experienceId,x]));
  return <div className="h-full w-full bg-[#f6f5f2] text-slate-800 flex flex-col">
    <div className="px-5 pt-5 pb-4 flex items-center justify-between border-b border-black/5 bg-white/70 backdrop-blur-xl"><div><div className="text-[11px] uppercase tracking-[0.18em] text-slate-400">Kphone Life</div><h1 className="text-xl font-semibold mt-1">他们刚刚在做什么</h1><p className="text-xs text-slate-400 mt-1">你不聊天的时候，角色也可以拥有自己的时间</p></div><button onClick={onClose} className="text-xs px-3 py-2 rounded-full bg-black/5">关闭</button></div>
    <div className="px-5 py-3 bg-white/50 flex gap-2 items-center flex-wrap"><button disabled={running} onClick={runNow} className="px-4 py-2 rounded-full bg-slate-900 text-white text-xs disabled:opacity-50">{running?'正在生活…':'现在让他们活动一下'}</button><button onClick={refresh} className="px-4 py-2 rounded-full bg-black/5 text-xs">刷新</button><button onClick={()=>{const n=saveLifeRuntimeSettings({proactiveEnabled:!settings.proactiveEnabled});setSettings(n);}} className="px-4 py-2 rounded-full bg-black/5 text-xs">主动联系：{settings.proactiveEnabled?'开':'关'}</button><label className="text-xs text-slate-500 flex items-center gap-2">间隔 <select value={settings.intervalMinutes} onChange={e=>setSettings(saveLifeRuntimeSettings({intervalMinutes:Number(e.target.value)}))} className="bg-white rounded-full px-2 py-1"><option value={1}>1 分钟</option><option value={5}>5 分钟</option><option value={10}>10 分钟</option><option value={30}>30 分钟</option><option value={60}>60 分钟</option></select></label></div>
    <div className="flex-1 overflow-y-auto px-5 py-4 space-y-3">{experiences.length===0?<div className="text-center text-sm text-slate-400 py-16">还没有生活记录。点上面的按钮让角色现在活动一下。</div>:experiences.map(item=>{const d=decisions.get(item.id);return <div key={item.id} className="bg-white rounded-3xl p-4 shadow-sm border border-black/5"><div className="flex items-start justify-between gap-3"><div><div className="text-xs text-slate-400">{item.charName} · {new Date(item.createdAt).toLocaleString()}</div><div className="font-medium mt-1">{item.title}</div><div className="text-sm text-slate-600 mt-1 leading-6">{item.detail}</div></div><span className="text-[10px] px-2 py-1 rounded-full bg-slate-100 text-slate-500">{item.activity}</span></div><div className="mt-3 pt-3 border-t border-black/5 text-xs"><span className="text-slate-400">💭 想法：</span><span className="text-slate-600">{item.thought}</span></div>{d&&<div className="mt-2 text-xs"><span className={d.shouldContact?'text-emerald-600':'text-slate-400'}>{d.shouldContact?'💬 决定联系你':'· 决定留在自己的时间里'}</span>{d.draftMessage&&<div className="mt-1 text-slate-600 bg-slate-50 rounded-2xl px-3 py-2">“{d.draftMessage}”</div>}</div>}</div>;})}</div>
  </div>;
};
export default KphoneLifeApp;
